//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calc()
        {
            this.Total_Transactions = new HashSet<Total_Transactions>();
        }
    
        public int ID { get; set; }
        public System.DateTime DT_reg { get; set; }
        public string LogLogin { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> ID_Money_Count { get; set; }
        public Nullable<int> ID_Money_Count2 { get; set; }
        public Nullable<int> ID_Money_Count3 { get; set; }
    
        public virtual Money_Count Money_Count { get; set; }
        public virtual Money_Count Money_Count1 { get; set; }
        public virtual Money_Count Money_Count2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total_Transactions> Total_Transactions { get; set; }
    }
}
