//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUMENT()
        {
            this.LISTs = new HashSet<LIST>();
        }
    
        public int ID { get; set; }
        public string FILE_NAME { get; set; }
        public long FILE_SIZE { get; set; }
        public string FILE_TYPE { get; set; }
        public byte[] FILE_CONTENT { get; set; }
        public System.DateTime DT_INSERT { get; set; }
        public Nullable<System.DateTime> DT_DELETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIST> LISTs { get; set; }
    }
}
