//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_Keeping
    {
        public int ID { get; set; }
        public string Room_Number { get; set; }
        public string Status { get; set; }
        public int Adults { get; set; }
        public System.DateTime DT_Registro { get; set; }
        public string LogLogin { get; set; }
    }
}
