//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostelEntities : DbContext
    {
        public HostelEntities()
            : base("name=HostelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_Type> Action_Type { get; set; }
        public virtual DbSet<Calc> Calcs { get; set; }
        public virtual DbSet<Calc_Type> Calc_Type { get; set; }
        public virtual DbSet<Card_Type> Card_Type { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENTs { get; set; }
        public virtual DbSet<EGALI_PASSWORDS> EGALI_PASSWORDS { get; set; }
        public virtual DbSet<EGALI_PASSWORDS_HISTORY> EGALI_PASSWORDS_HISTORY { get; set; }
        public virtual DbSet<House_Keeping> House_Keeping { get; set; }
        public virtual DbSet<LIST> LISTs { get; set; }
        public virtual DbSet<LIST_TYPE> LIST_TYPE { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Log_Type> Log_Type { get; set; }
        public virtual DbSet<Money_Count> Money_Count { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Report_Type> Report_Type { get; set; }
        public virtual DbSet<SHIFT_TYPE> SHIFT_TYPE { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Total_Transactions> Total_Transactions { get; set; }
        public virtual DbSet<Transaction_Type> Transaction_Type { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
