//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money_Count
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Money_Count()
        {
            this.Calcs = new HashSet<Calc>();
            this.Calcs1 = new HashSet<Calc>();
            this.Calcs2 = new HashSet<Calc>();
        }
    
        public int ID { get; set; }
        public int Qnt_1_Cent { get; set; }
        public int Qnt_2_Cents { get; set; }
        public int Qnt_5_Cents { get; set; }
        public int Qnt_10_Cents { get; set; }
        public int Qnt_20_Cents { get; set; }
        public int Qnt_50_Cents { get; set; }
        public int Qnt_1_Euro { get; set; }
        public int Qnt_2_Euros { get; set; }
        public int Qnt_5_Euros { get; set; }
        public int Qnt_10_Euros { get; set; }
        public int Qnt_20_Euros { get; set; }
        public int Qnt_50_Euros { get; set; }
        public int Qnt_100_Euros { get; set; }
        public int Qnt_200_Euros { get; set; }
        public int Qnt_500_Euros { get; set; }
        public decimal Total { get; set; }
        public System.DateTime DT_Reg { get; set; }
        public string LogLogin { get; set; }
        public int ID_Calc_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calc> Calcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calc> Calcs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calc> Calcs2 { get; set; }
        public virtual Calc_Type Calc_Type { get; set; }
    }
}
