//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public int ID_PRODUCT_TYPE { get; set; }
        public int AMOUNT { get; set; }
        public System.DateTime DT_Entrada { get; set; }
        public string LOGLOGIN { get; set; }
        public int ID_ACTION_TYPE { get; set; }
        public Nullable<int> ID_TOTAL_TRANSACTION { get; set; }
    
        public virtual Action_Type Action_Type { get; set; }
        public virtual Product_Type Product_Type { get; set; }
        public virtual Total_Transactions Total_Transactions { get; set; }
    }
}
