//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camada.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public System.DateTime DT_Reg { get; set; }
        public string LogLogin { get; set; }
        public string Reservation_Number { get; set; }
        public string GuestName { get; set; }
        public Nullable<int> ID_Transaction_Type { get; set; }
        public Nullable<int> ID_Payment_Type { get; set; }
        public Nullable<int> ID_Card_Type { get; set; }
        public string Description { get; set; }
        public decimal Total { get; set; }
        public int ID_Total_Transactions { get; set; }
    
        public virtual Card_Type Card_Type { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual Total_Transactions Total_Transactions { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
